// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ottzvwgukvkhluomiucu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90dHp2d2d1a3ZraGx1b21pdWN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MjMxNDIsImV4cCI6MjA3MzE5OTE0Mn0.V202tBmJCSnAakTcrobhjCzy63rZ8B7jDHAw-5ohYDE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});